### ISSUE TITLE
Unsupported operand type

### ISSUE THREAD

**Issue by bmann** [jamesob/discourse-archive#1]
Heya! I don't run a lot of Python, so I'm likely doing something wrong.

Running this command:

`discourse-archive -u https://example.com -t example`

I get this error:

```python
Traceback (most recent call last):
  File "/opt/homebrew/bin/discourse-archive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/archive.py", line 168, in main
    (posts_dir := target_dir / 'posts').mkdir(parents=True, exist_ok=True)
                  ~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

I'm on MacOS and used brew to install python3. Any help appreciated.

**Comment by jamesob** [comment]
@bmann thanks for the report! Indeed this is an (easily fixable) bug. I'll push a fix shortly.

**Comment by jamesob** [comment]
Fixed and cited you as co-author on the commit. Thanks again.

**Comment by jamesob** [comment]
Pushed to pypi: https://pypi.org/project/discourse-archive/0.1.3/
